### PR TITLE
cancancan as authorization for discussion

### LINKED ISSUE #60: Authorization support
If #58 is merged we need to add authorization. In this case it should be not possible to create a new Discussion for a non-user.

@mkasztelnik I assign this to you since you have experience with setting up auth systems.

### PR DESCRIPTION
**Pull request by mkasztelnik**
* CanCanCan added as authorization tool. 
* Only authenticated user is able to create new discussion
* User is able to delete only created disucssions

Fixes #60

### CODE REVIEW

**Comment by Nuanda** [comment]
Why did you add deleting the discussion to this branch?

**Comment by mkasztelnik** [comment]
To test cancan behaviour. If you want I can extract it into separate PR.

**Comment by Nuanda** [comment]
Yes, but you can easily test it on create, as I suggested. The thing is the delete operation cannot be as simple as it is and we need to think a little bit ahead here. I mean I would like to merge your auth code but not your delete code, at least not right away.

**Comment by mkasztelnik** [comment]
Discussion destroy removed, only create action authorized by cancan

**Comment by Nuanda** [comment]
Please, also remove the ujs delete handles from discussions.js and the .delete button styling in the layout.

**Comment by mkasztelnik** [comment]
done

**Comment by Nuanda** [comment]
:+1:

**Pull request merged**
