### PR TITLE
possiblity to destroy discussion if you created it

### PR DESCRIPTION
**Pull request by mkasztelnik**
These are the changes I originally made in the scope of #61. It can be used to start discussion when and who should be able to delete discussion. 

Possible scenarios:
  * user who create discussion is able to delete it (implemented in initial PR commit)
  * only discussion without comments can be deleted

Most probably cancan strategy used to delete discussion can be reused to edit discussion.

### CODE REVIEW

**Comment by Nuanda** [comment]
In my opinion:
- delete: only if original author and only if there are no comments of any other user inside (when there are no comments at all - do not ask for confirmation)
- edit (later):only if original author.

Now you see why I wanted to postpone this merge - since we need the comment model for that.

**Comment by mkasztelnik** [comment]
I believe that we can merge it even know. Please note that views and controller is created in such a way that all authorization data are located inside `app/models/ability.rb` class. When comments models will be introduced than we can change:

```ruby
can :destroy, Discussion, author_id: user.id
```

into

```ruby
can :destroy, Discussion do |discussion|
  discussion.user_id == user.id &&
    discussion.comments.count == 0
end
```

no further changes in controllers and views are necessary.

**Comment by Nuanda** [comment]
:+1:

**Comment by Nuanda** [comment]
I implemented this ability change in #70

**Pull request merged**
