### PR TITLE
Disqus integration

### PR DESCRIPTION
**Pull request by Nuanda**
I have added a space for per-zone discussion topics. Then I added the new Discussion::show routing and a simple view. This I load with Ajax.

Finally, I integrated with Disqus and added their js code to load a discussion. In order to test:
 - pick a FID of a zone (the red one, not a green district); it is shown in the popup
 - create with a console a new Discussion with a title and this fid
 - on the zone's popup, click the left yellow button
 - this will load the left panel with the new discussion
 - you load Disqus thread by clicking the discussion title in the left panel.

Current technical problem is that I had trouble setting up a per-zone threads. Disqus still insist on keeping only one thread for our entire site - this is probably due to it not working very well with a single URL app (it uses our global URL as the thread identifier).

Other, more general problems with Disqus are:
 - we do not control who can post - Disqus does - we can only moderate the thread
 - we are obviously dependent on them, so no possibility to change the discussion model and no control over the data.

Obvious advantages, besides not having to implement this, are full admin panel, automatic anti-spam and user control.

So we need to decide if we go further with Disqus or roll out our own discussion solution.

### CODE REVIEW

**Comment by mkasztelnik** [comment]
Another problem I see here is that you need to login once again. We can consider our own solution (unfortunately antyspanning, moderating need to be done by us) basing on:
  - https://github.com/jackdempsey/acts_as_commentable
  - https://github.com/elight/acts_as_commentable_with_threading

**Comment by Nuanda** [comment]
There is a SSO/auth solution provided by Disqus - but I haven't integrated it yet. I thought I wait will we decide what we do wrt discussions.

Antispam is not a big issue if we exclude (as I think we should) anonymous posting. So provided a spam bot is not able to register in our service, no spam should be posted. What I worry more about is moderation support - what automatic measures to use, the need to setup moderator admin dashboard, etc.

**Comment by Nuanda** [comment]
BTW I saw the two gems you list and I don't think they add anything valuable. Their most important feature is that you can comment on any piece of Model you have - we don't need that. Anyway, the model part of thee discussion module seems quite easy to implement for me.

**Comment by mkasztelnik** [comment]
Here is a nice discussion about automatic comments moderation http://stackoverflow.com/questions/3159499/auto-moderating-comments-with-rails. It seems like http://akismet.com could be used in our app (it is free for non-commertial sites).

**Comment by Nuanda** [comment]
Ok, I have removed Disqus integration for this merge request, so it could later go under review and be eventually merged. This gives us master branch that is ready for both - internal and external - discussion solutions. I will start the review process soon - I still need to add a simple discussion thread creation operation.

**Comment by Nuanda** [comment]
btw I think the js code to separate disqus threads on our internal discussion id works - I simply had broken testing setup, now it looks like creating new discussion for new features spawns new threads in disqus

**Comment by Nuanda** [comment]
All right, I think this is more or less ready to be merged.

If you know a neater solution for ajax "redirect" from action to action (here: from create to index) without passing extra params in the form, tell me.

For the time being the form and controller ignore any kind of errors (since there are no required fields apart from fid, which is supplied hidden, no user error can occur - only server errors are possible).

**Comment by mkasztelnik** [comment]
:+1:

You can return `js` part instead of whole `index` as a result of create action in order to insert new item into discussion. I have similar solution in dran and it works quite well.

**Comment by Nuanda** [comment]
I did a lot of what you propose in Locus. It didn't work well - perhaps because Locus has complex views (multi-ordering, filtering, different contexts...) so you never new where exactly to display the new item. Since then I prefer reloading partials.

However, perhaps this view is simple enough to do that...

**Comment by Nuanda** [comment]
@mkasztelnik Marek - since your last :+1: I have added a default discussions screen and also refactored the after-create response we have discussed earlier. Please, see the changes.

**Comment by mkasztelnik** [comment]
After new discussion is created title input field is not cleared - maybe it should be also hidden?

**Comment by Nuanda** [comment]
Fixed the form behavior on create.

**Comment by mkasztelnik** [comment]
:+1:

**Pull request merged**
